// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "chat-field"
                }, "Chat field"), React.createElement("div", {
                  className: "chat-input-field"
                }, "Input field"));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
