// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as App$SimpleChatAppPortfolio from "./App.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(App$SimpleChatAppPortfolio.make, { }), "root");

export {
  
}
/*  Not a pure module */
